runtime: nodejs16
env_variables:
  MONGO_DB_PASSWORD: $MONGO_DB_PASSWORD
  MONGO_CONNECT_STRING: $MONGO_CONNECT_STRING
  FIREBASE_APIKEY: $FIREBASE_APIKEY
  FIREBASE_AUTHDOMAIN: $FIREBASE_AUTHDOMAIN
  FIREBASE_PROJECTID: $FIREBASE_PROJECTID
  FIREBASE_STORAGEBUCKET: $FIREBASE_STORAGEBUCKET
  FIREBASE_MESSAGESENDERID: $FIREBASE_MESSAGESENDERID
  FIREBASE_APPID: $FIREBASE_APPID
  FIREBASE_MEASUREMENTID: $FIREBASE_MEASUREMENTID
