name: Deploy to Google App Engine
on:
  push:
    branches:
      - main
jobs:
  build:
    name: GAE Deploy

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: ${{ secrets.GCP_SECRETS }}

      - name: "Deploy to App Engine"
        uses: "google-github-actions/deploy-appengine@v0"
        with:
          deliverables: "./api/app.yaml"
          promote: false
          version: "v1"

      # Example of using the output
      - id: "test"
        run: 'curl "${{ steps.deploy.outputs.url }}"'
