name: Deploy to Google App Engine
on:
  push:
    branches:
      - main
jobs:
  build:
    name: GAE Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: api
    steps:
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: ${{ secrets.GCP_SECRETS }}
          work_dir: api

      - id: "deploy"
        uses: "google-github-actions/deploy-appengine@v0"

      # Example of using the output
      - id: "test"
        run: 'curl "${{ steps.deploy.outputs.url }}"'
